# create an exception


# data = int(input("Enter a number: "))
# data = data + 2
# print(data)



try:
   data = int(input("Enter a number: "))
   data = data + 2
   print(data)
except:
   print("Something is wrong")

